# Generated by Django 4.2.6 on 2023-10-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_page', '0005_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note',
            new_name='notes',
        ),
    ]
