# Generated by Django 4.2.6 on 2023-10-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_page', '0007_newwishlist_delete_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newwishlist',
            name='user',
        ),
    ]
