# Generated by Django 4.1.7 on 2023-10-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_alter_books_borrowed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='borrowed_by',
        ),
    ]
