# Generated by Django 4.1.7 on 2023-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0006_books_borrowed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='is_borrowed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
