# Generated by Django 4.2.6 on 2023-10-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_books_amount'),
        ('landingPage', '0007_books_borrowed_date_books_is_borrowed_and_more'),
    ]

    operations = [
    ]
