# Generated by Django 4.2.6 on 2023-10-26 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
        ('book_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.AddField(
            model_name='discussion',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='landingPage.books'),
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
