# Generated by Django 4.2.6 on 2023-10-26 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0002_remove_discussion_user_discussion_book_delete_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.CharField(default='', max_length=255)),
                ('discus', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_details.discussion')),
            ],
        ),
    ]
