# Generated by Django 4.2.6 on 2023-10-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
