# Generated by Django 4.2.6 on 2023-10-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0004_discussion_user_reply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='discus',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='book_details.discussion'),
        ),
    ]
