# Generated by Django 4.2.6 on 2023-10-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0006_discussion_date_added_reply_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_details.discussion'),
        ),
    ]
