# Generated by Django 4.2.6 on 2023-10-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_page', '0002_alter_member_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
