# Generated by Django 4.2.5 on 2023-12-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_page', '0004_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
